### ISSUE TITLE
Defaults settings do not take effect

### ISSUE THREAD

**Issue by qobilidop** [vsund/dotfiles#1]
Hi Valentin,

I have drawn inspirations from your repo for my own dotfiles. Thank you for making it public.

There is one issue with the install script. Since the `meta/base.yaml` is run by Dotbot separately from all the other configuration files, the defaults settings contained in it do not take effect. For example, if you try to link to a file in a directory not existing before, the directory will not be created automatically, contrary to the settings in `meta/base.yaml`.

The solution I'm thinking of now is to combine all the configuration files into a single one first, and then do a single Dotbot install. I have an implementation in my [dotfiles](https://github.com/qobilidop/dotfiles/tree/9e84005dee902d0b1214ace853c2c2beea630984) repo.

Thanks again for your repo based on which my repo is possible.

Best,
Bili

**Comment by vsund** [comment]
Oh thanks, great catch! Didn't notice this yet :)

I just pushed a fix for this (I've taken a slightly different approach). I'd like to call dotbot multiple times though, mostly to keep the status message "Configure xyz" (these already helped me a lot with debugging config errors).
